repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/Young-Naive-Simple/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
        args: ['--verbose', '--manifest-path', 'telegram_bot/Cargo.toml', '--']
        language: rust
    -   id: clippy
        args: ['--verbose', '--manifest-path', 'telegram_bot/Cargo.toml', '--']
        language: rust
    -   id: cargo-check
        args: ['--verbose', '--manifest-path', 'telegram_bot/Cargo.toml', '--']
        language: rust
