# A reusable workflow
name: Build and push docker

on:
  workflow_call:
    inputs:
      build_context:
        required: true
        type: string
      img_name:
        required: true
        type: string

jobs:
  reusable-build-push:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
      -
        name: lowercase username
        env:
          owner: ${{ github.repository_owner }}
        run: echo "user_lc=${owner,,}" >> ${GITHUB_ENV}
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.build_context }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.user_lc }}/${{ inputs.img_name }}:latest
